/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menuempleada;

import clinica.BuscarPaciente;
import clinica.Conection;
import clinica.Empleados;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruce
 */
public class CrearPacienteSecre extends javax.swing.JFrame {

    /**
     * Creates new form CrearPaciente
     */
    public CrearPacienteSecre() {
        initComponents();
        comnom.setVisible(false);
        conape.setVisible(false);
        comres.setVisible(false);
        coneda.setVisible(false);
        comcod4.setVisible(false);
        Cerrar();
    }
public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/caduceo (1).png"));


        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        tres = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tape = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BTguardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        tid = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        ttel = new javax.swing.JFormattedTextField();
        tedad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        treside = new javax.swing.JTextField();
        comnom = new javax.swing.JLabel();
        conape = new javax.swing.JLabel();
        comres = new javax.swing.JLabel();
        coneda = new javax.swing.JLabel();
        comcod4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paciente");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setText("Teléfono");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        tres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tresKeyTyped(evt);
            }
        });
        getContentPane().add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 140, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Responde");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Sexo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        tnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomActionPerformed(evt);
            }
        });
        tnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnomKeyTyped(evt);
            }
        });
        getContentPane().add(tnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Identidad");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Apellido");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        tape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tapeActionPerformed(evt);
            }
        });
        tape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tapeKeyTyped(evt);
            }
        });
        getContentPane().add(tape, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caduceo (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BTguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenessubmenucita/icons8-Guardar-40.png"))); // NOI18N
        BTguardar.setBorder(null);
        BTguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTguardarActionPerformed(evt);
            }
        });
        getContentPane().add(BTguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 83, 49));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenessubmenucita/icons8-Búsqueda-40.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 83, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Guardar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("Buscar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Masculino");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Femenino");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        try {
            tid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Edad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        try {
            ttel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 140, -1));

        tedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tedadKeyTyped(evt);
            }
        });
        getContentPane().add(tedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Reside");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 20));

        treside.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tresideKeyTyped(evt);
            }
        });
        getContentPane().add(treside, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 140, -1));

        comnom.setForeground(new java.awt.Color(255, 0, 0));
        comnom.setText("1");
        getContentPane().add(comnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 230, 10));

        conape.setForeground(new java.awt.Color(255, 0, 0));
        conape.setText("1");
        getContentPane().add(conape, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 270, 10));

        comres.setForeground(new java.awt.Color(255, 0, 0));
        comres.setText("1");
        getContentPane().add(comres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 270, 10));

        coneda.setForeground(new java.awt.Color(255, 0, 0));
        coneda.setText("1");
        getContentPane().add(coneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 270, 10));

        comcod4.setForeground(new java.awt.Color(255, 0, 0));
        comcod4.setText("1");
        getContentPane().add(comcod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 270, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tapeActionPerformed

    private void BTguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTguardarActionPerformed
        int tipo;
        Conection cc= new Conection();
        Connection cn =  cc.conexion();
        String id,tel,nom,ape,responde,reside,sexo;
        String sql="";
        int edad; 
       
        id= tid.getText();
        nom=tnom.getText();
        ape=tape.getText();
        edad=Integer.parseInt(tedad.getText());
        responde=tres.getText();
        tel=ttel.getText();
        reside=treside.getText();
        if(jRadioButton1.isSelected()){
            sexo="M";
        }else{
        sexo="F";}
        

       sql= "INSERT INTO persona(identidad,nombre,apellido,telefono,edad,sexo,responde,reside) VALUES(?,?,?,?,?,?,?,?)";

        try {
            PreparedStatement psd=  cn.prepareStatement(sql);
            psd.setString(1, id);
            psd.setString(2, nom);
            psd.setString(3, ape);
            psd.setString(4, tel);
            psd.setInt(5, edad);
            psd.setString(6, sexo);
            psd.setString(7, responde);
            psd.setString(8,reside);

            int n=psd.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BTguardarActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
    BuscarPaciente mAD=new BuscarPaciente();
        mAD.setVisible(true);
        dispose();
    }//GEN-LAST:event_tidActionPerformed

    private void tedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tedadKeyTyped
char c=evt.getKeyChar(); 
                   
          if(Character.isLetter(c)) { 
                          
              evt.consume(); 
              coneda.setVisible(true);
              coneda.setText("Solo numeros");
               
          }
          else{
              coneda.setVisible(false);
               
          } 
  
           if(c<'0' || c>'9')evt.consume();   // TODO add your handling code here:
    }//GEN-LAST:event_tedadKeyTyped

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresActionPerformed

    private void tresideKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tresideKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tresideKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
BuscarPacienteSecre b= new BuscarPacienteSecre();
b.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnomKeyTyped
int limite=35;
        if (tnom.getText().length()>=limite){
            evt.consume();
            comnom.setVisible(true);
            comnom.setText("Solo 35 Caracteres");
        }else{
        comnom.setVisible(false);
         
        }
    char c=evt.getKeyChar(); 
                   
          if(Character.isDigit(c)) { 
              evt.consume(); 
              comnom.setVisible(true);
              comnom.setText("Solo Letras");
               
          }else{
        comnom.setVisible(false);
         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tnomKeyTyped

    private void tapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tapeKeyTyped
int limite=35;
        if (tape.getText().length()>=limite){
            evt.consume();
            conape.setVisible(true);
            conape.setText("Solo 35 Caracteres");
        }else{
        conape.setVisible(false);
         
        }
    char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
               evt.consume();
               conape.setVisible(true);
               conape.setText("Solo Letras");
          } else{
        conape.setVisible(false);
         
        }         // TODO add your handling code here:
    }//GEN-LAST:event_tapeKeyTyped

    private void tresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tresKeyTyped
int limite=35;
        if (tape.getText().length()>=limite){
            evt.consume();
            comres.setVisible(true);
            comres.setText("Solo 35 Caracteres");
        }else{
        comres.setVisible(false);
         
        }
    char c=evt.getKeyChar(); 
          if(Character.isDigit(c)) { 
               evt.consume();
               comres.setVisible(true);
               comres.setText("Solo Letras");
          }else{
        comres.setVisible(false);
         
        }         // TODO add your handling code here:
    }//GEN-LAST:event_tresKeyTyped

    private void tnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPacienteSecre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPacienteSecre().setVisible(true);
            }
        });
    }
 public void Cerrar(){
    
        try{
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
            confirmarSalida();
            }
        });
    }catch(Exception e){
    e.printStackTrace();
    }
    }
    public void confirmarSalida(){
  int valor=JOptionPane.showConfirmDialog(this,"¿Esta Seguro de Cerrar?","Advertencia",JOptionPane.YES_NO_OPTION);
    if(valor==JOptionPane.YES_OPTION){
         Enfermera mAD=new Enfermera(); 
         mAD.setVisible(true);
         dispose();
    }
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel comcod4;
    private javax.swing.JLabel comnom;
    private javax.swing.JLabel comres;
    private javax.swing.JLabel conape;
    private javax.swing.JLabel coneda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField tape;
    private javax.swing.JTextField tedad;
    private javax.swing.JFormattedTextField tid;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tres;
    private javax.swing.JTextField treside;
    private javax.swing.JFormattedTextField ttel;
    // End of variables declaration//GEN-END:variables
}
