/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Bruce
 */
public class VerCita extends javax.swing.JFrame {

    /**
     * Creates new form VerCita
     */
    public VerCita() {
        initComponents();
        ldoc.setVisible(false);
        Cerrar();
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/caduceo (1).png"));


        return retValue;
    }
    public void Reporte(){
    Conection cc= new Conection();
try{
        String rutaInforme=System.getProperty("user.dir")+"/src/Reportes/CitaDoctor.jasper";
        Map parametros= new HashMap();
        parametros.put("ffecha",ffecha.getText());
        parametros.put("coddoc",Integer.parseInt(doc.getText()));
        JasperPrint informe = JasperFillManager.fillReport (rutaInforme,parametros,cc.conexion());
        JasperViewer ventanavisor = new JasperViewer(informe, false);
        ventanavisor.setTitle("Cita del Dia");
        ventanavisor.setVisible(true);
                }
        catch (HeadlessException | JRException  e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Error en el Reporte","Error",JOptionPane.ERROR_MESSAGE );
        }
}
    
public void mostrarFecha(String valor1){
Conection cc= new Conection();
Connection cn =  cc.conexion();
        DefaultTableModel modelo = new DefaultTableModel();
       
        modelo.addColumn("Fecha-Hora");
        modelo.addColumn("Identidad Paciente");
        modelo.addColumn("Nombre Paciente");
        
        modelo.addColumn("Nombre Doctor");
        
        jTableCliente.setModel(modelo);
        String sql = "";
        if(valor1.equals(""))
        {
            sql = "SELECT cita.fecha,cita.hora,cita.identidad,persona.nombre,persona.apellido,cita.cod_doctor,empleado.nombre,empleado.apellido FROM cita INNER JOIN persona ON cita.identidad=persona.identidad INNER JOIN empleado ON cita.cod_doctor=empleado.cod_empleado";
        }
        else
        {
            
            sql = "SELECT cita.fecha,"
                    + "cita.hora,"
                    + "cita.identidad,"
                    + "persona.nombre,"
                    + "persona.apellido,"
                    + "empleado.nombre,"
                    + "empleado.apellido,"
                    + "cita.cod_doctor  FROM cita INNER JOIN persona ON cita.identidad=persona.identidad INNER JOIN empleado ON cita.cod_doctor=empleado.cod_empleado WHERE fecha='"+valor1+"' AND cod_doctor='"+Integer.parseInt(doc.getText())+"'";
        }
    String []datos = new String [5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos [0] = rs.getString(1)+" "+rs.getString(2);
                datos [1] = rs.getString(3);
                datos [2] = rs.getString(4)+" "+rs.getString(5);
                datos [3] = rs.getString(6)+" "+rs.getString(7);
                
                
               
            modelo.addRow(datos);
            }
           // jtb_consulta_venta_auto.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(BuscarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }}
    /**]=}
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        doc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ffecha = new javax.swing.JTextField();
        ldoc = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel4.setText("Doctor");

        jButton1.setText("Ingresar");

        jLabel2.setText("Fecha/hora");

        jLabel3.setText("Paciente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas Doctor-Fecha");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(861, 488));
        setPreferredSize(new java.awt.Dimension(861, 488));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenessubmenucita/icons8-Visible-40.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 70, 60));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 750, 290));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Imprimir");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 60, -1));

        doc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                docFocusLost(evt);
            }
        });
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        getContentPane().add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Codigo Doctor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Fecha");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        ffecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffechaActionPerformed(evt);
            }
        });
        getContentPane().add(ffecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 150, -1));

        ldoc.setText("jLabel1");
        getContentPane().add(ldoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenessubmenucita/icons8-Imprimir-40.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Ver");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 30, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
  
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mostrarFecha(ffecha.getText());     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ffechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffechaActionPerformed

    private void docFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_docFocusLost
    ldoc.setVisible(true);
  int cod;
        ResultSet rs = null;
        Statement st = null;
       try {
             
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/medicor2","root","");
              st = conn.createStatement();
              rs = st.executeQuery("SELECT nombre,apellido,cod_tipoempleado from empleado where cod_empleado ='"+doc.getText()+"'");
//              SELECT `nombre`, `apellido` FROM `empleado`  WHERE `cod_tipoempleado`= 1
            while(rs.next()){
            cod=rs.getInt(3);
            if (cod!=1){
                ldoc.setText("Este Empleado no es Medico");
                return;
            }else{
               String x;
               String v = rs.getString("nombre");
               String tmpStrObtenido1 = rs.getString("apellido");
           
               String v2= "Nombre: "+v+" "+tmpStrObtenido1;
              
               ldoc.setText(v2);
               
               
           }}
            
          conn.close();
         } catch (Exception e) {
             
             return;
         }  
       
    }//GEN-LAST:event_docFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     Reporte();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCita().setVisible(true);
            }
        });
    }
     public void Cerrar(){
    
        try{
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
            confirmarSalida();
            }
        });
    }catch(Exception e){
    e.printStackTrace();
    }
    }
    public void confirmarSalida(){
  int valor=JOptionPane.showConfirmDialog(this,"¿Esta Seguro de Cerrar?","Advertencia",JOptionPane.YES_NO_OPTION);
    if(valor==JOptionPane.YES_OPTION){
         Cita mAD=new Cita(); 
         mAD.setVisible(true);
         dispose();
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doc;
    private javax.swing.JTextField ffecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel ldoc;
    // End of variables declaration//GEN-END:variables
}
